<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-09T14:51:00Z" name="Default suite" finished-at="2022-03-09T14:51:59Z" duration-ms="58825">
    <groups>
    </groups>
    <test started-at="2022-03-09T14:51:00Z" name="Default test" finished-at="2022-03-09T14:51:59Z" duration-ms="58825">
      <class name="com.automationFramework.uiTests.VerifyProductCounts">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07]" started-at="2022-03-09T20:21:00Z" name="launchBrowser" finished-at="2022-03-09T20:21:03Z" duration-ms="2342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07]" started-at="2022-03-09T20:21:03Z" name="beforeMethod" finished-at="2022-03-09T20:21:03Z" duration-ms="4" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.automationFramework.uiTests.VerifyProductCounts.testVerifyProductCounts()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testVerifyProductCounts()[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07]" started-at="2022-03-09T20:21:03Z" name="testVerifyProductCounts" description="validate follow to facebook and verify product counts for color orange" finished-at="2022-03-09T20:21:59Z" duration-ms="55680" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [7]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [7]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.automationFramework.uiTests.VerifyProductCounts.testVerifyProductCounts(VerifyProductCounts.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyProductCounts -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07]" started-at="2022-03-09T20:21:59Z" name="afterMethod" finished-at="2022-03-09T20:21:59Z" duration-ms="166" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testVerifyProductCounts status=FAILURE method=VerifyProductCounts.testVerifyProductCounts()[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:com.automationFramework.uiTests.VerifyProductCounts@63fdab07]" started-at="2022-03-09T20:21:59Z" name="endTest" finished-at="2022-03-09T20:21:59Z" duration-ms="611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.automationFramework.uiTests.VerifyProductCounts -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
